### ISSUE TITLE
[Pregunta] ¿Cuando estara disponible en el Firefox Marketplace?

### ISSUE THREAD

**Issue by VictorOsorioMedrano** [mozillahispano/twitta#16]
Lo siento si la pregunta es muy apresurada, sin embargo desde hace ya un buen tiempo estoy deseoso de saber la respuesta :)

**Comment by willyaranda** [comment]
Tan pronto como pueda terminar lo que falta.

**Comment by VictorOsorioMedrano** [comment]
Gracias por la respuesta @willyaranda , la estaré esperando con ansias :+1:
